
version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: nata
      POSTGRES_PASSWORD: 312230


  node-app:
      build: .
      image: node-app:1.0
      ports:
        - '9999:9999'

